camp/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views
from camp_reg import settings
from django.conf.urls.static import static


urlpatterns = [
    # path()
    path(r'', views.welcome, name='welcome'),
    url(r'^base_signup/$', views.base_signup, name='base_signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login/<user>/', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/<child>$', views.register, name='register'),
    url(r'^home/$', views.home, name='home'),
    url(r'^parent_details/$', views.parent_details, name='parent_details'),
    url(r'^view/$', views.view, name='view'),
    url(r'^edit_student/$', views.edit_student, name='edit_student'),
    url(r'^list/$', views.list, name='list'),
    url(r'^router/$', views.router, name='router'),
    url(r'^download_all/$', views.download_all, name='download_all'),
    url(r'^student/$', views.student, name='student'),
    url(r'^download_resume/$', views.download_resume, name='download_resume'),
    url(r'^reset/$', views.reset, name='reset'),
    url('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

camp_reg/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('camp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'', include(('camp.urls', 'camp'), namespace='camp')),
    # path('accounts/signup/parent/', students.StudentSignUpView.as_view(), name='student_signup'),
    # path('accounts/signup/staff/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

camp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.files.storage import FileSystemStorage
from camp_reg import settings

fs = FileSystemStorage(location=settings.MEDIA_ROOT)



class User(AbstractUser):
    is_parent = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)


class Parent(models.Model):
    address = models.CharField(max_length=200)
    mobile_1 = models.CharField(max_length=13)
    mobile_2 = models.CharField(max_length=13, blank=True)
    work_address = models.CharField(max_length=200, blank=True)
    work_mobile = models.CharField(max_length=13, blank=True)
    email = models.EmailField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Student(models.Model):
    # SAMALIYAH_SUMMER = 'SR'
    # SAMALIYAH_SPRING = 'SG'
    # ATHURAYA = 'AT'
    # RAMADAN_FESTIVAL = 'RF'
    #
    # CAMP_CHOICES = [
    #     ('samaliyah_summer', SAMALIYAH_SUMMER),
    #     ('samaliyah_spring', SAMALIYAH_SPRING),
    #     ('athuraya', ATHURAYA),
    #     ('ramadan_festival', RAMADAN_FESTIVAL)
    # ]

    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=10, default='male')
    school = models.CharField(max_length=200)
    grade = models.CharField(max_length=10)
    dob = models.DateField()
    contact = models.CharField(max_length=13)
    email = models.EmailField()
    camp = models.CharField(max_length=100)
    picture = models.ImageField(storage=fs)
    id_card = models.FileField(storage=fs, default=None)
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE, null=True)

camp/forms.py
from .models import User
from .models import Student, Parent
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'is_parent', 'is_staff')


class ParentForm(forms.ModelForm):
    class Meta:
        model = Parent
        fields = '__all__'


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

camp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect, HttpResponse
from .forms import UserForm, StudentForm, ParentForm
from .models import Parent, Student, User
from django.contrib.auth import login as auth_login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from .decorators import *
import os
import io
from camp_reg import settings
from .pdf_generator import PdfGenerate as pdf
from reportlab.platypus import SimpleDocTemplate
from reportlab.lib.pagesizes import letter, landscape
from django.http import FileResponse


def welcome(request):
    return render(request, 'camp/welcome.html', {})


def base_signup(request):
    if request.method == 'POST':

        post_values = request.POST.copy()
        user_type = post_values.get('user_type')
        if user_type == 'parent':
            post_values['is_parent'] = True
            post_values['is_staff'] = False
        elif user_type == 'staff':
            post_values['is_parent'] = False
            post_values['is_staff'] = True
        form = UserForm(post_values)

        if form.is_valid():
            form.save()
            user_name = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=user_name, password=password)
            auth_login(request, user)
            return redirect(f'/login?user={user_type}')
        else:
            messages.error(request, form.errors)
    else:
        form = UserForm()
    return render(request, 'camp/base_signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                auth_login(request, user)
                user_type = request.POST.get('user_type')
                page = None
                if user_type == 'parent':
                    page = '/home'
                elif user_type == 'staff':
                    page = '/list'
                return HttpResponseRedirect(page)
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            messages.error(request, ('Invalid login details given!'))
            return HttpResponseRedirect(request.path_info)

    else:
        user = request.GET.get('user')
        id = "lg"
        if user == "parent" or user == "staff":
            id = ""
        return render(request, 'camp/login.html', {'user': request.GET.get('user'), 'id': id})


@login_required(login_url="/login")
@staff_required
def list(request):
    students = None
    camp = None
    if request.method == "POST":
        all_list = False
        try:
            camp = request.POST.get('camp')
            students = Student.objects.filter(camp=camp).prefetch_related('parent')
            if not students:
                messages.success(request, ('No Students in this camp!'))
                students = None
        except Exception as e:
            messages.error(request, (e.__str__()))
            students = None
        if 'pdf' in request.POST or 'print' in request.POST:

            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=0)

            _pdf = pdf()
            _pdf.AddLogo()
            _pdf.AddTable(students, camp)

            doc.build(_pdf.story)

            # FileResponse sets the Content-Disposition header so that browsers
            # present the option to save the file.
            buffer.seek(0)

            as_attachment = True
            if 'print' in request.POST:
                as_attachment = False
            return FileResponse(buffer, as_attachment=as_attachment, filename=f'Students_{camp}.pdf')
    else:
        all_list = True

    return render(request, 'camp/list.html', {'students': students, 'camp': camp, 'all_list': all_list})


@login_required(login_url="/login")
@staff_required
def download_all(request):
    camps = []
    students = []
    try:
        students = Student.objects.all()
        camps = students.values_list('camp', flat=True).distinct()
    except Exception as e:
        messages.error(request, (e.__str__()))

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=0)

    _pdf = pdf()
    _pdf.AddLogo()
    for camp in camps:
        camp_st = students.filter(camp=camp)
        _pdf.AddTable(camp_st, camp)

    doc.build(_pdf.story)

    if 'pdf' in request.POST:
        as_attachment = True
    elif 'print' in request.POST:
        as_attachment = False
    else:
        as_attachment = False

    buffer.seek(0)
    return FileResponse(buffer, as_attachment=as_attachment, filename=f'All Students.pdf')


@login_required(login_url="/login")
@parent_required
def register(request):
    print(request.POST)
    p_id = None
    student = None
    try:
        parent = Parent.objects.get(user=request.user.id)
        p_id = parent.id
    except Exception as e:
        messages.error(request, ('Parent details are missing. Please add your details first.'))

    if request.method == 'POST':
        post_values = request.POST.copy()
        post_values['parent'] = p_id
        try:
            st = get_object_or_404(Student, pk=request.POST.get('st_id'))
        except:
            st = None
        form = StudentForm(post_values, request.FILES, instance=st)

        if form.is_valid():
            try:
                form.save()
                messages.success(request, ('Child Details Added Successfully!'))
            except Exception as e:
                print(e.__str__())

            return HttpResponseRedirect('/home')
        else:
            messages.error(request, form.errors)
    else:
        child_id = request.GET.get('child')

        if child_id:
            student = Student.objects.get(pk=child_id)

    return render(request, 'camp/register.html', {'child': student})


@login_required(login_url="/login")
@staff_required
def download_resume(request):
    print(request.POST.get('student_id'))
    if request.method == 'POST':
        try:
            student = Student.objects.select_related('parent').get(pk=request.POST.get('student_id'))
        except:
            student = None
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=0)

        _pdf = pdf()
        _pdf.AddLogo()
        _pdf.AddResume(student)
        doc.build(_pdf.story)

        buffer.seek(0)
        as_attachment = False
        if 'pdf' in request.POST:
            as_attachment = True
        return FileResponse(buffer, as_attachment=as_attachment, filename=f'Student_{student.name}.pdf')


@login_required(login_url="/login")
@parent_required
def home(request):
    return render(request, 'camp/home.html', {})


@login_required(login_url="/login")
@parent_required
def parent_details(request):

    try:
        parent = get_object_or_404(Parent, user=request.user.id)
        if parent.user_id != request.user.id:
            return HttpResponseForbidden()
    except:
        parent = None

    post_values = None
    if request.method == 'POST':
        post_values = request.POST.copy()
        post_values['user'] = request.user.id

    form = ParentForm(post_values, instance=parent)

    if request.method == 'POST':

        if form.is_valid():
            try:
                form.save()
                messages.success(request, ('Details Added Successfully!'))
            except Exception as e:
                messages.error(request, (e.__str__()))

            return HttpResponseRedirect('/home')
        else:
            messages.error(request, form.errors)

    return render(request, 'camp/parent_details.html', {'form': form})


@login_required(login_url="/login")
@parent_required
def view(request):
    p_id = None
    try:
        parent = Parent.objects.get(user=request.user.id)
        p_id = parent.id
    except Exception as e:
        messages.error(request, ('No children added!'))

    if request.method == "POST":
        if "edit" in request.POST:
            ch_id = request.POST.get('child')
            st = Student.objects.get(pk=ch_id)
            print(st)
            return HttpResponseRedirect(f'/register?child={st.id}')
        elif "delete" in request.POST:
            ch_id = request.POST.get('child')
            Student.objects.filter(pk=ch_id).delete()

    students = Student.objects.filter(parent=p_id)
    return render(request, 'camp/view.html', {'children': students})


@login_required(login_url="/login")
@parent_required
def edit_student(request):
    return render(request, 'camp/edit_student.html', {})


@login_required(login_url="/login")
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/login')


@login_required(login_url="/login")
def router(request):
    try:
        user_id = request.user.id
        user = User.objects.get(pk=user_id)
        if user.is_parent == True and user.is_staff == False:
            page = '/home'
        elif user.is_staff == True and user.is_parent == False:
            page = '/list'
        else:
            logout(request)

        return HttpResponseRedirect(page)
    except Exception as e:
        messages.error(request, '(Something went wrong!)')


@login_required(login_url='/login')
def student(request):
    student = None
    try:
        st_id = request.GET.get('id')
        student = Student.objects.select_related('parent').get(pk=st_id)

camp/templates/camp/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>eCamp</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'camp:base_signup' %}">Sign Up</a>
  <a class="navbar-brand" href="{% url 'camp:login' %}">Login</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
    <div class="container">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small>
                            <sup>x</sup>
                        </small>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  </body>
</html>

camp/templates/camp/base_signup.html
{% extends 'camp/base.html' %}
{% load static %}

{% block content %}
    <div class="user_type_select">
        <button type="button" class="btn btn-dark user_select" value="parent">I'm a parent</button>
        <button type="button" class="btn btn-dark user_select" value="staff">I'm a staff</button>
    </div>
    <div id="su">
    <form method="post" class="styled">
        {% csrf_token %}
        {% for field in form %}
            {% if field.name != "is_parent" and field.name != "is_staff" %}

                <label>
                    <p class="label-txt">{{ field.label_tag }}</p><br>
                    {% if field.name == "password1" or field.name == "password2" %}
                        <input type="password" class="input" name="{{ field.name }}">
                    {% else %}
                        <input type="text" class="input" name="{{ field.name }}">
                    {% endif %}
                    <div class="line-box">
                      <div class="line"></div>
                    </div>
                </label><br>
            {% endif %}
        {% endfor %}
        <input type="hidden" id="user_type" name="user_type" value="">
        <button type="submit">Sign up</button>
    </form>
    </div>

{% endblock %}

camp/templates/camp/home.html
{% extends 'camp/pbase.html' %}

{% block content %}
    <div>
        <ul class="parent_menu">
            <li><a href="{% url 'camp:parent_details' %}">Add parent details</a></li>
            <li><a href="{% url 'camp:register' %}">Register your child</a></li>
            <li><a href="{% url 'camp:view' %}">View Children</a></li>
        </ul>
    </div>
{% endblock %}

camp/templates/camp/list.html
{% extends 'camp/pbase.html' %}

{% block content %}
<form method="post" class="topMargin">
{% csrf_token %}

{% if students == None %}
<!--<a href="{% url 'camp:home' %}" class="float-left text-info"> Go To Home </a>-->
<h3 class="text-center font-bold pt-4 pb-5 mb-5 text-dark">Select Camp</h3>
<form method="post">
{% csrf_token %}
    <div class="camp_select">
        <button type="submit" class="btn btn-success camp_btn">Samaliyah Summer camp</button>
        <button type="submit" class="btn btn-success camp_btn">Samaliyah Spring Camp</button>
        <button type="submit" class="btn btn-success camp_btn">Athuraya Camp</button>
        <button type="submit" class="btn btn-success camp_btn">Ramadan Festival</button>
        <input type="hidden" value="" name="camp">
    </div>
</form>

{% else %}
    <h3 class="text-center font-bold pt-4 pb-5 mb-5 text-dark">Students list</h3>

    <div class="list-group students">
        <form method="post">
            <input type="hidden" value="{{ camp|default_if_none:'' }}" name="camp">
            <span>
                <button type="submit" class="pull-right download" name="print"><i class="fa fa-print"></i></button>
                <button type="submit" class="pull-right download" name="pdf"><i class="fa fa-download"></i></button>
            </span>
        </form>
      {% for st in students %}

        <a href="/student?id={{ st.id }}">
                    <p class="list-group-item list-group-item-action list-group-item-success">{{ st.name }}</p>
            </a>
    <!--      <a href="#" class="list-group-item list-group-item-action float-left">{{ child.name }}-->
    <!--          <i class="fa fa-trash icon-margin right"></i><i class="fa fa-edit icon-margin right"></i></a>-->
      {% endfor %}

    </div>

{% endif %}



</form>

{% if all_list %}
       <form method="post" action="{% url 'camp:download_all' %}">
           {% csrf_token %}
           <span class="right right-space">
                <button type="submit" class="" name="pdf"><i class="fa fa-download"></i> Download All <i class="fa fa-file-pdf-o"></i></button>
                <button type="submit" class="" name="print"><i class="fa fa-print"></i> Print All</button>
            </span>
       </form>

{% endif %}
{% endblock %}

camp/templates/camp/login.html
{% extends 'camp/base.html' %}
{% block content %}
{% if user != 'staff' and user != 'parent' %}
    <div class="user_type_select">
        <button type="button" class="btn btn-dark lg_user_select" value="parent">I'm a parent</button>
        <button type="button" class="btn btn-dark lg_user_select" value="staff">I'm a staff</button>
    </div>
{% endif %}

    <div class="tabcontent" style="display:block;">
        <br>
            <div id="{{ id }}">
            <form method="post" class="styled">
                  {% csrf_token %}

                <label>
                    <p class="label-txt">Username</p>
                    <input type="text" class="input" name="username">
                    <div class="line-box">
                      <div class="line"></div>
                    </div>
                </label><br>

                <label>
                    <p class="label-txt">Password</p>
                    <input type="password" class="input" name="password">
                    <div class="line-box">
                      <div class="line"></div>
                    </div>
                </label><br>
                <input type="hidden" id="lg_user_type" name="user_type" value="{{ user|default_if_none:'' }}">
                <input type="submit" name="" value="Login">
                <a href="{% url 'camp:reset' %}">Forgot Password</a>
            </form>
                <a href="https://play.google.com/store/apps/details?id=com.esmartvision.torathemirates" title="Download Mobile App" target="_blank" style="color:black !important;">
                    Download App <i class="fab fa-google-play"></i>
                </a>
            </div>

    </div>
{% endblock %}

camp/templates/camp/pbase.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/reg.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/camp.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/resume.css' %}">
    <link rel="stylesheet" href="{% static 'css/radio.css' %}">
<!--    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">-->
    <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
    <title>eCamp</title>
  </head>
  <body>

       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
           <span style="color:white;">Welcome, {{ user.username}}</span>
          <a class="navbar-brand ml-auto" href="{% url 'camp:logout' %}">Logout</a>
       </nav>

       <div>
           {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small>
                            <sup>x</sup>
                        </small>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
       </div>

       <div class="logos">
           <div class="second-logo">
               <a href="{% url 'camp:router' %}" class="left-logo text-info">
                   <img src="../static/images/ehc3.png">
               </a>

           </div>

           <div class="third-logo">
               <img src="../static/images/ehc4.png">
           </div>

<!--           <div class="logo-contain">-->
<!--&lt;!&ndash;               <a href="{% url 'camp:router' %}"><img src="../static/images/ehc.gif" class="logo"><br></a>&ndash;&gt;-->
<!--               <a href="{% url 'camp:router' %}" class="left-logo text-info"> Go To Home </a>-->
<!--           </div>-->
       </div>



        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="{% static 'js/reg.js' %}"></script>
    <script src="{% static 'js/preg.js' %}"></script>
  </body>

camp/templates/camp/reset.html
{% extends 'camp/base.html' %}
{% block content %}
<h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

camp/templates/camp/student_resume.html
{% extends 'camp/pbase.html' %}

{% block content %}
    {% if student %}


        <div class="resume">

            <table>
                <tr>
                    <td class="td1">
                        <img src="/media/{{ student.picture }}" height="150px" width="150px">
                    </td>
                    <td class="td2" align="left">
                        Name: {{ student.name }}<br>
                        Gender: {{ student.gender }}<br>
                        Camp: {{ student.camp }}<br>
                        School: {{ student.school }}<br>
                        Grade: {{ student.grade }}<br>
                        Date of Birth: {{ student.dob }}<br>
                        Mobile Number: {{ student.contact }}<br>
                        Email: {{ student.email }}<br>
                        Parent Name: {{ student.parent.user.username }} <br>
                        Address: {{ student.parent.address }}<br>
                        Parent Mobile 1: {{ student.parent.mobile_1 }}<br>
                        Parent Mobile 2: {{ student.parent.mobile_2 }}<br>
                        Work Address: {{ student.parent.work_address }}<br>
                        Work Mobile: {{ student.parent.work_mobile }}<br>
                        Parent Email: {{ student.parent.email }}<br>
                        ID Card: <a href="/media/{{ student.id_card }}"><i class="fa fa-file-pdf-o"></i></a>
                    </td>
                </tr>
            </table>

            {% if type == 'staff' %}
                <form method="post" action="{% url 'camp:download_resume' %}">
                    {% csrf_token %}
                    <div class="right right-space">
                        <button type="submit" class="pull-right" name="pdf"><i class="fa fa-download"></i></button>
                        <button type="submit" class="pull-right" name="print"><i class="fa fa-print"></i></button>
                    </div>
                        <input type="hidden" name="student_id" value="{{ student.id }}">
                </form>
            {% endif %}

        </div>

    {% endif %}

    {% if type == 'parent' %}
        <div class="outer">
            <a href="{% url 'camp:view' %}" class="left-logo text-info view_list">View Children</a>
        </div>
    {% elif type == 'staff' %}
        <div class="outer">
            <a href="{% url 'camp:list' %}" class="left-logo text-info view_list">Back</a>
        </div>
    {% endif %}
{% endblock %}

camp/templates/camp/welcome.html
{% extends 'camp/base.html' %}

{% block content %}
<div class="center">
  <img src="../static/images/ehc.gif">
  <h2>Welcome to eCamp</h2>
</div>


{% endblock %}